* 용어
** [[https://en.wikipedia.org/wiki/HTML][HTML(hyper text markup language)]] 
   - hyper text markup language
** [[https://en.wikipedia.org/wiki/HTML][Hyper Text]] 
   - text displayed on a computer display or other electronic devices with references (hyperlinks)
   - to other text that the reader can immediately access.
** [[https://en.wikipedia.org/wiki/Markup_language][Markup Language]] 
   - a system for *annotating* a document in a way that is syntactically distinguishable from the text,[1]
   - meaning when the document is processed for display, the markup language is not shown,
   - and is only used to format the text.
** Anotation
   - extra information associated with a particular point in a document or other piece of information.
   - It can be a note that includes a comment or explanation.
** [[https://en.wikipedia.org/wiki/World_Wide_Web_Consortium][W3C]] 
   - World Wide Web Consortium
   - the main international standards organization for the World Wide Web.
** [[https://en.wikipedia.org/wiki/World_Wide_Web][World Wide Web]] 
   - commonly known as the Web,
   - an information system where documents and other web resources are identified
   - by Uniform Resource Locators (URLs, such as https://example.com/)
   - The resources of the Web are transferred via the Hypertext Transfer Protocol (*HTTP*)
   - and may be accessed by users by a software application called a _web browser_
   - and are published by a software application called a _web server_.
** [[https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol][Hypertext Transfer Protocol (HTTP)]] 
   - an Session layer protocol for distributed, collaborative, hypermedia information systems.
   - the foundation of data communication for the World Wide Web.
     
** [[https://en.wikipedia.org/wiki/Hypermedia][Hypermedia]]
   - an extension of the term hypertext, is a nonlinear medium of information that includes graphics, 
   - audio, video, plain text and hyperlinks.
   - The World Wide Web is a classic example of hypermedia,
   - whereas a non-interactive cinema presentation is an example of standard multimedia
   - due to the absence of hyperlinks. 
     
** [[http://html5test.com/]]
